baseURL = 'https://magiconline.github.io/'
languageCode = 'en-us'
title = "魔法张的Blog"

# theme 
theme = "paper"

[params]
    github="magiconline"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"   
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"